In [1]:
import json    

In [2]:
with open("sarcasm.json", 'r' )  as f:
    datastore = json.load(f)

In [3]:
headline=[]
labels=[]
for item in datastore:
    headline.append(item['headline'])
    labels.append(item['is_sarcastic'])

In [4]:
print(headline)

["former versace store clerk sues over secret 'black code' for minority shoppers", "the 'roseanne' revival catches up to our thorny political mood, for better and worse", "mom starting to fear son's web series closest thing she will have to grandchild", 'boehner just wants wife to listen, not come up with alternative debt-reduction ideas', 'j.k. rowling wishes snape happy birthday in the most magical way', "advancing the world's women", 'the fascinating case for eating lab-grown meat', 'this ceo will send your kids to school, if you work for his company', 'top snake handler leaves sinking huckabee campaign', "friday's morning email: inside trump's presser for the ages", 'airline passengers tackle man who rushes cockpit in bomb threat', 'facebook reportedly working on healthcare features and apps', "north korea praises trump and urges us voters to reject 'dull hillary'", "actually, cnn's jeffrey lord has been 'indefensible' for a while", 'barcelona holds huge protest in support of refug

In [5]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [6]:
tokenizer= Tokenizer(num_words=5000,oov_token='<OOV>')
tokenizer.fit_on_texts(headline)
word_index=tokenizer.word_index
print(word_index)

{'<OOV>': 1, 'to': 2, 'of': 3, 'the': 4, 'in': 5, 'for': 6, 'a': 7, 'on': 8, 'and': 9, 'with': 10, 'is': 11, 'new': 12, 'trump': 13, 'man': 14, 'from': 15, 'at': 16, 'about': 17, 'you': 18, 'this': 19, 'by': 20, 'after': 21, 'up': 22, 'out': 23, 'be': 24, 'how': 25, 'as': 26, 'it': 27, 'that': 28, 'not': 29, 'are': 30, 'your': 31, 'his': 32, 'what': 33, 'he': 34, 'all': 35, 'just': 36, 'who': 37, 'has': 38, 'will': 39, 'more': 40, 'one': 41, 'into': 42, 'report': 43, 'year': 44, 'why': 45, 'have': 46, 'area': 47, 'over': 48, 'donald': 49, 'u': 50, 'day': 51, 'says': 52, 's': 53, 'can': 54, 'first': 55, 'woman': 56, 'time': 57, 'like': 58, 'her': 59, "trump's": 60, 'old': 61, 'no': 62, 'get': 63, 'off': 64, 'an': 65, 'life': 66, 'people': 67, 'obama': 68, 'now': 69, 'house': 70, 'still': 71, "'": 72, 'women': 73, 'make': 74, 'was': 75, 'than': 76, 'white': 77, 'back': 78, 'my': 79, 'i': 80, 'clinton': 81, 'down': 82, 'if': 83, '5': 84, 'when': 85, 'world': 86, 'could': 87, 'we': 88, 'th

In [7]:
headline_seq=tokenizer.texts_to_sequences(headline)
paded_headline = pad_sequences(headline_seq,padding='post',maxlen=40)
print(paded_headline)

[[ 308    1  679 ...    0    0    0]
 [   4    1 3338 ...    0    0    0]
 [ 145  838    2 ...    0    0    0]
 ...
 [   1    9   68 ...    0    0    0]
 [1541  392 4164 ...    0    0    0]
 [   1 1647    6 ...    0    0    0]]


In [8]:
paded_headline.shape

(26709, 40)

In [9]:
 from sklearn.model_selection import train_test_split

In [10]:
import numpy as np

In [11]:
labels = np.array(labels)

In [12]:
x_train,x_test,y_train,y_test = train_test_split(paded_headline,labels,test_size=0.25, random_state=42)

In [13]:
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Embedding,Dense,Flatten,GlobalAveragePooling1D

In [14]:
def sarc_model():
    model = Sequential()
    model.add(Embedding(5000,16,input_length=40))
    model.add(Flatten())
    model.add(Dense(8,activation='relu'))
    model.add(Dense(1,activation='sigmoid'))
    return model

In [15]:
model = sarc_model()
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 40, 16)            80000     
_________________________________________________________________
flatten (Flatten)            (None, 640)               0         
_________________________________________________________________
dense (Dense)                (None, 8)                 5128      
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 9         
Total params: 85,137
Trainable params: 85,137
Non-trainable params: 0
_________________________________________________________________


In [16]:
model.fit(x_train,y_train,validation_data=(x_test,y_test),epochs=15)

Epoch 1/15
626/626 [==============================] - 1s 938us/step - loss: 0.4771 - accuracy: 0.7480 - val_loss: 0.3421 - val_accuracy: 0.8453
Epoch 2/15
626/626 [==============================] - 1s 858us/step - loss: 0.2568 - accuracy: 0.8943 - val_loss: 0.3261 - val_accuracy: 0.8561
Epoch 3/15
626/626 [==============================] - 1s 861us/step - loss: 0.1888 - accuracy: 0.9265 - val_loss: 0.3280 - val_accuracy: 0.8621
Epoch 4/15
626/626 [==============================] - 1s 850us/step - loss: 0.1395 - accuracy: 0.9495 - val_loss: 0.3605 - val_accuracy: 0.8594
Epoch 5/15
626/626 [==============================] - 1s 862us/step - loss: 0.0961 - accuracy: 0.9692 - val_loss: 0.4028 - val_accuracy: 0.8544
Epoch 6/15
626/626 [==============================] - 1s 847us/step - loss: 0.0607 - accuracy: 0.9836 - val_loss: 0.4638 - val_accuracy: 0.8503
Epoch 7/15
626/626 [==============================] - 1s 857us/step - loss: 0.0349 - accuracy: 0.9918 - val_loss: 0.5292 - val_accuracy:

In [17]:
def sarc_model2():
    model = Sequential()
    model.add(Embedding(5000,16,input_length=40))
    model.add(GlobalAveragePooling1D())
    model.add(Dense(8,activation='relu'))
    model.add(Dense(1,activation='sigmoid'))
    return model

In [18]:
model2=sarc_model2()
model2.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
model2.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 40, 16)            80000     
_________________________________________________________________
global_average_pooling1d (Gl (None, 16)                0         
_________________________________________________________________
dense_2 (Dense)              (None, 8)                 136       
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 9         
Total params: 80,145
Trainable params: 80,145
Non-trainable params: 0
_________________________________________________________________


In [19]:
model2.fit(x_train,y_train,validation_data=(x_test,y_test),epochs=30)

Epoch 1/30
626/626 [==============================] - 1s 1ms/step - loss: 0.6182 - accuracy: 0.6512 - val_loss: 0.4681 - val_accuracy: 0.8146
Epoch 2/30
626/626 [==============================] - 1s 1ms/step - loss: 0.3785 - accuracy: 0.8454 - val_loss: 0.3591 - val_accuracy: 0.8446
Epoch 3/30
626/626 [==============================] - 1s 1ms/step - loss: 0.3017 - accuracy: 0.8779 - val_loss: 0.3424 - val_accuracy: 0.8488
Epoch 4/30
626/626 [==============================] - 1s 1ms/step - loss: 0.2667 - accuracy: 0.8905 - val_loss: 0.3469 - val_accuracy: 0.8491
Epoch 5/30
626/626 [==============================] - 1s 908us/step - loss: 0.2431 - accuracy: 0.9026 - val_loss: 0.3460 - val_accuracy: 0.8482
Epoch 6/30
626/626 [==============================] - 1s 910us/step - loss: 0.2271 - accuracy: 0.9095 - val_loss: 0.3557 - val_accuracy: 0.8518
Epoch 7/30
626/626 [==============================] - 1s 875us/step - loss: 0.2147 - accuracy: 0.9140 - val_loss: 0.3798 - val_accuracy: 0.8431
