In [1]:
import json    

<h2> Read Data </h2>

In [2]:
with open("sarcasm.json", 'r' )  as f:  
    datastore = json.load(f)

In [3]:
headline=[]
labels=[]
for item in datastore:
    headline.append(item['headline'])
    labels.append(item['is_sarcastic'])

<h2>Preprocessing data</h2>

In [5]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [6]:
tokenizer= Tokenizer(num_words=5000,oov_token='<OOV>')
tokenizer.fit_on_texts(headline)
word_index=tokenizer.word_index


In [7]:
headline_seq=tokenizer.texts_to_sequences(headline)
paded_headline = pad_sequences(headline_seq,padding='post',maxlen=40)
print(paded_headline)

[[ 308    1  679 ...    0    0    0]
 [   4    1 3338 ...    0    0    0]
 [ 145  838    2 ...    0    0    0]
 ...
 [   1    9   68 ...    0    0    0]
 [1541  392 4164 ...    0    0    0]
 [   1 1647    6 ...    0    0    0]]


In [8]:
paded_headline.shape

(26709, 40)

In [9]:
 from sklearn.model_selection import train_test_split

In [10]:
import numpy as np

In [11]:
labels = np.array(labels)

<h2> Splitting Data into train and test dataset

In [12]:
x_train,x_test,y_train,y_test = train_test_split(paded_headline,labels,test_size=0.25, random_state=42)

In [13]:
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Embedding,Dense,Flatten,GlobalAveragePooling1D,LSTM,Bidirectional

<h2> lstm Model

In [14]:
def sarc_model():
    model = Sequential()
    model.add(Embedding(5000,16,input_length=40))
    model.add(Bidirectional(LSTM(32)))
    model.add(Dense(8,activation='relu'))
    model.add(Dense(1,activation='sigmoid'))
    return model

In [15]:
model = sarc_model()
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 40, 16)            80000     
_________________________________________________________________
bidirectional (Bidirectional (None, 64)                12544     
_________________________________________________________________
dense (Dense)                (None, 8)                 520       
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 9         
Total params: 93,073
Trainable params: 93,073
Non-trainable params: 0
_________________________________________________________________


In [16]:
model.fit(x_train,y_train,validation_data=(x_test,y_test),epochs=15)

Epoch 1/15
626/626 [==============================] - 6s 10ms/step - loss: 0.4453 - accuracy: 0.7766 - val_loss: 0.3443 - val_accuracy: 0.8464
Epoch 2/15
626/626 [==============================] - 5s 9ms/step - loss: 0.2759 - accuracy: 0.8831 - val_loss: 0.3416 - val_accuracy: 0.8509
Epoch 3/15
626/626 [==============================] - 5s 8ms/step - loss: 0.2309 - accuracy: 0.9057 - val_loss: 0.3564 - val_accuracy: 0.8473
Epoch 4/15
626/626 [==============================] - 5s 8ms/step - loss: 0.1964 - accuracy: 0.9239 - val_loss: 0.3642 - val_accuracy: 0.8497
Epoch 5/15
626/626 [==============================] - 5s 8ms/step - loss: 0.1605 - accuracy: 0.9402 - val_loss: 0.3964 - val_accuracy: 0.8486
Epoch 6/15
626/626 [==============================] - 5s 8ms/step - loss: 0.1253 - accuracy: 0.9556 - val_loss: 0.4795 - val_accuracy: 0.8413
Epoch 7/15
626/626 [==============================] - 5s 8ms/step - loss: 0.1029 - accuracy: 0.9653 - val_loss: 0.4917 - val_accuracy: 0.8420
Epoch

<h2> Nural Network Model

In [17]:
def sarc_model2():
    model = Sequential()
    model.add(Embedding(5000,16,input_length=40))
    model.add(GlobalAveragePooling1D())
    model.add(Dense(8,activation='relu'))
    model.add(Dense(1,activation='sigmoid'))
    return model

In [18]:
model2=sarc_model2()
model2.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
model2.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 40, 16)            80000     
_________________________________________________________________
global_average_pooling1d (Gl (None, 16)                0         
_________________________________________________________________
dense_2 (Dense)              (None, 8)                 136       
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 9         
Total params: 80,145
Trainable params: 80,145
Non-trainable params: 0
_________________________________________________________________


In [19]:
model2.fit(x_train,y_train,validation_data=(x_test,y_test),epochs=30)

Epoch 1/30
626/626 [==============================] - 3s 4ms/step - loss: 0.6408 - accuracy: 0.6334 - val_loss: 0.5258 - val_accuracy: 0.7938
Epoch 2/30
626/626 [==============================] - 2s 4ms/step - loss: 0.4117 - accuracy: 0.8351 - val_loss: 0.3740 - val_accuracy: 0.8441
Epoch 3/30
626/626 [==============================] - 2s 4ms/step - loss: 0.3173 - accuracy: 0.8712 - val_loss: 0.3450 - val_accuracy: 0.8507
Epoch 4/30
626/626 [==============================] - 2s 4ms/step - loss: 0.2775 - accuracy: 0.8868 - val_loss: 0.3393 - val_accuracy: 0.8524
Epoch 5/30
626/626 [==============================] - 3s 4ms/step - loss: 0.2519 - accuracy: 0.8985 - val_loss: 0.3473 - val_accuracy: 0.8461
Epoch 6/30
626/626 [==============================] - 2s 4ms/step - loss: 0.2344 - accuracy: 0.9072 - val_loss: 0.3486 - val_accuracy: 0.8543
Epoch 7/30
626/626 [==============================] - 2s 4ms/step - loss: 0.2209 - accuracy: 0.9124 - val_loss: 0.3579 - val_accuracy: 0.8519
Epoch 